# Generated by Django 5.0.6 on 2024-07-04 10:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SandwichModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام ساندوچ')),
                ('price', models.DecimalField(decimal_places=0, max_digits=15, verbose_name='قیمت ساندویچ')),
                ('image', models.ImageField(upload_to='sandwich')),
                ('offer_price', models.DecimalField(blank=True, decimal_places=0, max_digits=15, null=True, verbose_name='قیمت پس از تخفیف')),
                ('offer', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)], verbose_name='درصد تخفیف')),
            ],
            options={
                'verbose_name': 'ساندویچ',
                'verbose_name_plural': 'ساندویچ ها',
            },
        ),
    ]
