# Generated by Django 5.0.6 on 2024-07-04 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Food_Module', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sandwichmodel',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='فعال / غیرفعال'),
        ),
    ]
