# Generated by Django 5.0.6 on 2024-07-08 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Food_Module', '0004_saucemodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='sandwichmodel',
            name='is_special',
            field=models.BooleanField(default=False, verbose_name='پیشنهاد ویژه'),
        ),
    ]
