# Generated by Django 5.0.6 on 2024-07-04 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home_Module', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitebannermodel',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='فعال / غیرفعال'),
        ),
    ]
