# Generated by Django 5.0.2 on 2024-07-20 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home_Module', '0002_sitebannermodel_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettingmodel',
            name='email',
            field=models.EmailField(default='eiliyazanganeh1385@gmail.com', max_length=254, verbose_name='ایمیل سایت'),
            preserve_default=False,
        ),
    ]
